server:
  port: 9091
spring:
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: purchasesdb

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic